apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/freitasleoalves/fiap-tc-5-gitops.git
        revision: HEAD
        directories:
          - path: apps/*/overlays/prod
  template:
    metadata:
      name: 'app-{{ index .path.segments 1 }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/freitasleoalves/fiap-tc-5-gitops.git
        targetRevision: HEAD
        path: '{{ .path.path }}'
      destination:
        server: https://kubernetes.default.svc
        # Sem prefixo de produto no namespace (diferente da Fase 3/4, que
        # usava "togglemaster-<app>") — aqui o namespace é o nome do app
        # direto: "ngo", "donation", "volunteer", "notification".
        namespace: '{{ index .path.segments 1 }}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
