apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addon-otel-collector-logs
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-collector
      targetRevision: 0.173.0
      helm:
        releaseName: otel-collector-logs
        valueFiles:
          - $values/addons/otel-collector-logs/values.yaml

    - repoURL: https://github.com/freitasleoalves/fiap-tc-5-gitops.git
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
