apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: notification
resources:
  - ../../base
  - secrets.yaml
images:
  - name: acrsolidarytechprod.azurecr.io/notification-service
    newTag: latest
