apiVersion: batch/v1
kind: Job
metadata:
  name: db-init-donation
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: init-donation-db
          image: postgres:15-alpine
          command: ["/bin/sh", "-c", "psql \"$DATABASE_URL\" -f /sql/init.sql"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: donation-database-url
          volumeMounts:
            - name: sql
              mountPath: /sql
      volumes:
        - name: sql
          configMap:
            name: db-init-donation
