apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: donation
resources:
  - ../../base
  - configmap.yaml
  - db-init-job.yaml
  - hpa.yaml
  - ingress.yaml
  - secrets.yaml
images:
  - name: acrsolidarytechprod.azurecr.io/donation-service
    newTag: latest
